set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER startist WITH PASSWORD '123456' NOCREATEDB;
  CREATE USER stalbum WITH PASSWORD '123456' NOCREATEDB;
  CREATE USER stsong WITH PASSWORD '123456' NOCREATEDB;
  CREATE USER stauth WITH PASSWORD '123456' NOCREATEDB;
  
  CREATE DATABASE st_artist OWNER startist;
  CREATE DATABASE st_album OWNER stalbum;
  CREATE DATABASE st_song OWNER stsong;
  CREATE DATABASE st_auth OWNER stauth;

EOSQL