DROP TABLE IF EXISTS ALBUM;

CREATE TABLE ALBUM (
   ID             VARCHAR(255) PRIMARY KEY NOT NULL,
   NAME           TEXT    NOT NULL,
   DESCRIPTION    TEXT    NOT NULL,
   COVER_URL      TEXT,
   SONGS_ID       TEXT    NOT NULL
);