spring:
  application.name: song-service
  profiles.active: dev
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

flyway.baselineOnMigrate: true

server:
  port: 0