spring:
  application.name: song-service
  datasource:
    url: jdbc:postgresql://localhost:5432/st_song
    username: stsong
    password: 123456
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

flyway.baselineOnMigrate: true

server:
  port: 0