spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/st_artist
      username: startist
      password: 123456
  jpa:
      hibernate.ddl-auto: validate
      properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
