version: '3.1'
services:
  st-artist:
    image: st-artist
    environment:
      PROFILE: prod
      ST_ARTIST_POSTGRES_DB_HOST: dbapi.cwbjjpmrugyl.sa-east-1.rds.amazonaws.com
      ST_ARTIST_POSTGRES_DB_PORT: 5432
      ST_ARTIST_POSTGRES_DB_SCHEME: st_artist
      ST_ARTIST_POSTGRES_DB_USERNAME: startist
      ST_ARTIST_POSTGRES_DB_PASSWORD: 123456
      ST_ARTIST_CONSUL_HOST: public-lb-1567832265.sa-east-1.elb.amazonaws.com
      ST_ARTIST_CONSUL_PORT: 80
  st-song:
      image: st-song
      environment:
        PROFILE: prod
        ST_ARTIST_POSTGRES_DB_HOST: dbapi.cwbjjpmrugyl.sa-east-1.rds.amazonaws.com
        ST_ARTIST_POSTGRES_DB_PORT: 5432
        ST_ARTIST_POSTGRES_DB_SCHEME: st_artist
        ST_ARTIST_POSTGRES_DB_USERNAME: startist
        ST_ARTIST_POSTGRES_DB_PASSWORD: 123456
        ST_ARTIST_CONSUL_HOST: public-lb-1567832265.sa-east-1.elb.amazonaws.com
        ST_ARTIST_CONSUL_PORT: 80
