zuul:
  ignoreLocalService: false
  prefix: /api
  routes:
    album:
      path: /album/**
      serviceId: album-service
      sensitiveHeaders:
    song:
      path: /song/**
      serviceId: song-service
      sensitiveHeaders:
    artist:
      path: /artist/**
      serviceId: artist-service
      sensitiveHeaders:
server:
  port: 8085

logging:
  level:
   org.springframework: INFO
   com.netflix: DEBUG

spring:
  application:
    name: st-gateway

host.full.dns.auth.link: http://localhost:8089

app.client:
  id: spring-security-oauth2-read-write-client
  secret: spring-security-oauth2-read-write-client-password1234

auth.server.schem: http