DROP TABLE IF EXISTS SONG;

CREATE TABLE SONG (
   ID             VARCHAR(255) PRIMARY KEY NOT NULL,
   NAME           TEXT    NOT NULL,
   DURATION       TIME    NOT NULL,
   ARTIST_ID      VARCHAR(255) NOT NULL,
   ALBUM_ID       VARCHAR(255) NOT NULL,
   URL_VIDEO      TEXT    NOT NULL
);